US014 Create Band
KeelanScott/all_tables_api pull request #10
Opened 2023-07-25 13:23 UTC by JamesMcKee-Kainos

2023-07-25 13:53 UTC, joshuasy10 requested changes

2023-07-25 13:53 UTC, joshuasy10 commented on src/main/java/org/kainos/ea/controller/TrainingCourseController.java
> +
remove whitespace

2023-07-25 13:53 UTC, joshuasy10 commented on src/main/java/org/kainos/ea/dao/BandDao.java
> +
remove space

2023-07-25 13:53 UTC, joshuasy10 commented on src/main/java/org/kainos/ea/dao/CompetencyDao.java
> +
remove space

2023-07-25 13:53 UTC, joshuasy10 commented on src/main/java/org/kainos/ea/dao/JobRoleDao.java
> +                    rs.getString("bands.level"),
superb

2023-07-25 13:53 UTC, joshuasy10 commented on src/main/java/org/kainos/ea/dao/TrainingCourseDao.java
> +
remove space

2023-07-25 13:53 UTC, joshuasy10 commented on src/main/java/org/kainos/ea/model/Band.java
> -    }
fab

2023-07-25 13:53 UTC, joshuasy10 commented on src/main/java/org/kainos/ea/model/BandRequest.java
> +import com.fasterxml.jackson.annotation.JsonProperty;
outstanding

2023-07-25 13:53 UTC, joshuasy10 commented on src/main/java/org/kainos/ea/service/CompetencyService.java
> +
remove space

2023-07-25 13:53 UTC, joshuasy10 commented on src/main/java/org/kainos/ea/service/TrainingCourseService.java
> +
remove space

2023-07-25 13:53 UTC, joshuasy10 commented on src/test/java/integration/controller/BandControllerIntegrationTest.java
> +import org.kainos.ea.model.BandRequest;
remove spaces

2023-07-25 13:53 UTC, joshuasy10 commented on src/test/java/integration/controller/TrainingCourseControllerIntegrationTest.java
> +
remove spaces

2023-07-25 13:53 UTC, joshuasy10 commented on src/test/java/unit/controller/BandControllerUnitTest.java
> +
remove space

2023-07-25 13:53 UTC, joshuasy10 commented on src/test/java/unit/controller/BandControllerUnitTest.java
> +
remove space

2023-07-25 13:53 UTC, joshuasy10 commented on src/test/java/unit/controller/BandControllerUnitTest.java
> +
remove space

2023-07-25 13:53 UTC, joshuasy10 commented on src/test/java/unit/controller/CompetencyControllerUnitTest.java
> +
you know the drill big man

2023-07-25 13:53 UTC, joshuasy10 commented on src/test/java/unit/service/CompetencyServiceUnitTest.java
> +
spaces lad

2023-07-25 13:53 UTC, joshuasy10 commented on src/test/java/unit/validator/BandCompetencyValidatorTest.java
> +
spaces

2023-07-25 13:53 UTC, joshuasy10 commented on src/test/java/unit/validator/BandValidatorTest.java
> +
remove spaces

2023-07-25 14:23 UTC, joshuasy10 requested changes

2023-07-25 14:23 UTC, joshuasy10 commented on .idea/uiDesigner.xml
plz put .idea in gitignore

2023-07-25 14:23 UTC, joshuasy10 commented on sql/init_script.sql
> +        level VARCHAR(30) UNSIGNED NOT NULL,
luvly stuff

2023-07-25 14:23 UTC, joshuasy10 commented on src/main/java/org/kainos/ea/service/CompetencyService.java
remove the space

2023-07-25 14:23 UTC, joshuasy10 commented on src/test/java/unit/controller/CompetencyControllerUnitTest.java
> +
remove space

2023-07-25 14:23 UTC, joshuasy10 commented on src/test/java/unit/controller/TrainingCourseControllerUnitTest.java
> +
remove space

2023-07-25 14:27 UTC, joshuasy10 approved these changes

2023-07-26 08:13 UTC, joshuasy10 requested changes

2023-07-26 08:13 UTC, joshuasy10 commented on src/main/java/org/kainos/ea/controller/JobRoleController.java
> -        } catch (DatabaseConnectionException | FailedToGetJobRoleException e) {
why is this removed?

2023-07-26 08:13 UTC, joshuasy10 commented on src/main/java/org/kainos/ea/service/JobRoleService.java
> +        } catch (SQLException | DatabaseConnectionException e) {
why is this being changed?

2023-07-26 08:13 UTC, joshuasy10 approved these changes

2023-07-26 09:45 UTC, shaunganley requested changes
I recommend merging all of your POST endpoints so we pass all of the data in with 1 request object, I'm happy if you want to keep the dao separate but might want to combine the service layers. Also recommend merging the GET endpoints for training and competencies so you only have to make 1 HTTP request to populate both dropdown lists

2023-07-26 09:45 UTC, shaunganley commented on src/test/java/integration/controller/BandControllerIntegrationTest.java
> +    }
can you add a test for the validation failing

2023-07-26 09:45 UTC, shaunganley commented on src/test/java/unit/controller/BandControllerUnitTest.java
> +    }
needs tests for exceptions being thrown

2023-07-26 09:45 UTC, shaunganley commented on src/test/java/unit/service/BandServiceUnitTest.java
> +    }
this suggests that the tests are dependant on objects created outside of the test method. please create the objects required inside the test method so this isn't required

2023-07-26 09:45 UTC, shaunganley commented on src/test/java/unit/service/BandServiceUnitTest.java
> +    void createBand_shouldThrowSqlException_whenDaoThrowsSqlException() throws SQLException, DatabaseConnectionException {
method name doesn't matched the assertThrows exception

2023-07-26 09:45 UTC, shaunganley commented on src/test/java/unit/service/BandServiceUnitTest.java
> +    void createBand_shouldThrowFailedToCreateBandException_whenDaoThrowsSQLException() throws SQLException, DatabaseConnectionException {
this is testing the same scenario as above. can we change one of them to check the DatabaseConnectionException scenario

2023-07-26 09:45 UTC, shaunganley commented on src/test/java/unit/service/BandServiceUnitTest.java
> +    BandService bandService = new BandService(bandDao);
don't you also need to provide the validator so you can mock it out?

2023-07-26 09:45 UTC, shaunganley commented on src/test/java/unit/service/BandServiceUnitTest.java
> +}
rather than setting the name can you mock the validator and force it to throw the exception

2023-07-26 09:45 UTC, shaunganley commented on src/test/java/unit/service/CompetencyServiceUnitTest.java
> +    @Test
add another test for the DatabaseConnectionException scenario

2023-07-26 09:45 UTC, shaunganley commented on src/test/java/unit/service/CompetencyServiceUnitTest.java
> +    }
don't set invalid data, instead mock out the validator and have it throw the exception

2023-07-26 09:45 UTC, shaunganley commented on src/test/java/unit/service/TrainingCourseServiceUnitTest.java
> +    @Test
add another test for DatabaseConnectionException

2023-07-26 09:45 UTC, shaunganley commented on src/test/java/unit/validator/BandCompetencyValidatorTest.java
> +    }
create the object in each test method so you don't need this

2023-07-28 08:20 UTC, joshuasy10 requested changes

2023-07-28 08:20 UTC, joshuasy10 commented on src/main/java/org/kainos/ea/all_tables_apiApplication.java
> +        environment.jersey().register(new CompetencyController(new CompetencyService(new CompetencyDao(), new BandCompetencyValidator())));
youe are referencying Competancy Dao and Trianing Dao multiple times, instead of creating more ibjects create them once and pass in that one object to both constructors

2023-07-28 08:20 UTC, joshuasy10 commented on src/main/java/org/kainos/ea/service/TrainingCourseService.java
> +            trainingCourseListList = trainingCourseDao.getAllTrainingCourses();
return this in one line and remove the 2 unnecessary lines

2023-07-28 14:42 UTC, shaunganley requested changes
nearly there

2023-07-28 14:42 UTC, shaunganley commented on .idea/uiDesigner.xml
shouldn't be here

2023-07-28 14:42 UTC, shaunganley commented on src/main/java/org/kainos/ea/controller/BandController.java
> +    public Response getAllBands() {
not needed

2023-07-28 14:42 UTC, shaunganley commented on src/main/java/org/kainos/ea/dao/BandDao.java
> +    public List<Band> getAllBands() throws SQLException, DatabaseConnectionException {
not required

2023-07-28 14:42 UTC, shaunganley commented on src/main/java/org/kainos/ea/model/BandCompetencyRequest.java
> +    public BandCompetencyRequest(@JsonProperty("competencyId") int competencyID,
shouldn't be needed

2023-07-28 14:42 UTC, shaunganley commented on src/main/java/org/kainos/ea/model/BandRequest.java
> +public class BandRequest {
not needed with BandWithDetailsRequest

2023-07-28 14:42 UTC, shaunganley commented on src/main/java/org/kainos/ea/model/BandTrainingCourse.java
> +    public BandTrainingCourse(@JsonProperty("bandId") int bandId,
not needed with BandWithDetailsRequest

2023-07-28 14:42 UTC, shaunganley commented on src/main/java/org/kainos/ea/model/BandWithDetailsRequest.java
> +    public BandWithDetailsRequest(@JsonProperty("band") BandRequest band,
use band model

2023-07-28 14:42 UTC, shaunganley commented on src/main/java/org/kainos/ea/model/BandWithDetailsRequest.java
> +                                  @JsonProperty("bandCompetencies") BandCompetencyRequest[] bandCompetencies,
use BandCompetency model

2023-07-28 14:42 UTC, shaunganley commented on src/main/java/org/kainos/ea/service/BandService.java
> +            }
move logic to bandValidator

2023-07-28 14:42 UTC, shaunganley commented on src/main/java/org/kainos/ea/service/BandService.java
> +    public List<Band> getAllBands() throws FailedToGetBandsException {
remove

2023-07-28 14:42 UTC, shaunganley commented on src/main/java/org/kainos/ea/validator/BandCompetencyValidator.java
> +    public boolean isValidBandCompetency(BandCompetencyRequest bandCompetency) throws InvalidBandCompetencyException {
can you verify the competency ids exist in the db while validating

2023-07-28 14:42 UTC, shaunganley commented on src/main/java/org/kainos/ea/validator/BandValidator.java
> +public class BandValidator {
can you validate the training ids exist in the db

2023-07-28 14:42 UTC, shaunganley commented on src/test/java/integration/controller/BandControllerIntegrationTest.java
> +    void createBand_shouldReturnId(){
test the failed validation scenario

2023-07-28 14:42 UTC, shaunganley commented on src/test/java/integration/controller/JobRoleControllerIntegrationTest.java
> +        System.out.println(response);
remove

2023-07-31 09:53 UTC, JamesMcKee-Kainos commented on src/main/java/org/kainos/ea/model/BandCompetencyRequest.java
> +    public BandCompetencyRequest(@JsonProperty("competencyId") int competencyID,
What bit do you mean here, sorry?

2023-07-31 09:55 UTC, JamesMcKee-Kainos commented on src/main/java/org/kainos/ea/model/BandRequest.java
> +public class BandRequest {
So should the name, level, and responsibilities directly be part of BandWithDetailsRequest instead?

2023-07-31 09:59 UTC, JamesMcKee-Kainos commented on src/main/java/org/kainos/ea/model/BandWithDetailsRequest.java
> +    public BandWithDetailsRequest(@JsonProperty("band") BandRequest band,
BandRequest is used instead of Band here, as since the band hasn't been created yet, we don't have its ID

2023-07-31 10:01 UTC, JamesMcKee-Kainos commented on src/main/java/org/kainos/ea/model/BandWithDetailsRequest.java
> +                                  @JsonProperty("bandCompetencies") BandCompetencyRequest[] bandCompetencies,
We don't have the band's ID yet, so BandCompetency can't be used. I also just noticed that BandCompetency isn't actually used anywhere at the minute, so I removed it

2023-07-31 11:15 UTC, JamesMcKee-Kainos commented on src/main/java/org/kainos/ea/validator/BandValidator.java
> +public class BandValidator {
The training IDs aren't currently part of the BandRequest, but the BandWithDetailsRequest. Should BandRequest be merged into BandWithDetailsRequest, or should a separate validator be made to check that the training IDs exist?

2023-07-31 12:33 UTC, ccurran01 commented on src/main/java/org/kainos/ea/controller/CompetencyController.java
> +        }
@JamesMcKee-Kainos Looks like This comment still needs to be addressed

2023-07-31 12:46 UTC, JamesMcKee-Kainos commented on src/main/java/org/kainos/ea/controller/CompetencyController.java
> +        }
That comment is now out of date, after making it Shaun sent me a message on Teams saying "ignore the API comment that asks you to merge the GET competencies and training endpoints, I hadn't realised you were going to split them up and use session"

2023-08-02 09:31 UTC, joshuasy10 approved these changes

2023-08-03 10:19 UTC, merged