Updating ReadMe file
KeelanScott/all_tables_api pull request #11
Opened 2023-07-25 14:51 UTC by jedgar3

Updating readme file for run and test commands

2023-07-25 14:58 UTC, joshuasy10 approved these changes

2023-07-26 08:01 UTC, shaunganley requested changes
can you add details about environment variables that are required. does `mvn clean test` also run integration tests?

2023-07-26 08:26 UTC, joshuasy10 approved these changes

2023-07-26 08:41 UTC, shaunganley approved these changes

2023-07-26 08:47 UTC, merged