US012 add new role
KeelanScott/all_tables_api pull request #12
Opened 2023-07-26 13:09 UTC by joshuasy10

2023-07-26 13:34 UTC, jedgar3 requested changes

2023-07-26 13:34 UTC, jedgar3 commented on src/main/java/org/kainos/ea/controller/BandController.java
Lokking good!

2023-07-26 13:34 UTC, jedgar3 commented on src/main/java/org/kainos/ea/controller/CapabilityController.java
Good job

2023-07-26 13:34 UTC, jedgar3 commented on src/main/java/org/kainos/ea/dao/BandDao.java
> +
Remove whitespace

2023-07-26 13:34 UTC, jedgar3 commented on src/main/java/org/kainos/ea/model/JobRoleRequest.java
> +    public JobRoleRequest(String name, int band, int capability) {
Does specification need to be passed in as it is being set in this constructor. Is the constructor needed if it has the same parameters as the one above

2023-07-26 13:34 UTC, jedgar3 commented on src/main/java/org/kainos/ea/validator/JobRoleValidator.java
Good validation work Josh

2023-07-26 13:34 UTC, jedgar3 commented on src/test/java/integration/controller/JobRoleControllerIntegrationTest.java
> +    void createJobRole_shouldReturn201_whenCreated() {
should this method name say should return 200

2023-07-26 13:34 UTC, jedgar3 commented on src/main/java/org/kainos/ea/validator/JobRoleValidator.java
> +        if(jobRoleRequest.getSpecification().length() > 255){
You have checked that specifictaion isn't more than 255 characters which is good, but you should also check if it is null because it is set to not null in the database

2023-07-26 13:34 UTC, jedgar3 commented on src/test/java/validator/JobRoleValidatorTest.java
Add test for where specification is an empty string

2023-07-26 13:48 UTC, joshuasy10 commented on src/main/java/org/kainos/ea/dao/BandDao.java
> +
done

2023-07-26 13:48 UTC, joshuasy10 commented on src/main/java/org/kainos/ea/model/JobRoleRequest.java
> +    public JobRoleRequest(String name, int band, int capability) {
done

2023-07-26 13:48 UTC, joshuasy10 commented on src/main/java/org/kainos/ea/validator/JobRoleValidator.java
thanks bro

2023-07-26 13:49 UTC, joshuasy10 commented on src/test/java/integration/controller/JobRoleControllerIntegrationTest.java
> +    void createJobRole_shouldReturn201_whenCreated() {
done

2023-07-26 13:49 UTC, joshuasy10 commented on src/test/java/validator/JobRoleValidatorTest.java
done

2023-07-26 13:52 UTC, jedgar3 approved these changes
Outsatnding work Josh

2023-07-27 09:50 UTC, shaunganley requested changes

2023-07-27 09:50 UTC, shaunganley commented on src/main/java/org/kainos/ea/controller/BandController.java
> +    }
not required

2023-07-27 09:50 UTC, shaunganley commented on src/main/java/org/kainos/ea/controller/CapabilityController.java
> +    }
not required

2023-07-27 09:50 UTC, shaunganley commented on src/main/java/org/kainos/ea/controller/JobRoleController.java
> +            return Response.ok(jobRoleService.createJobRole(jobRoleRequest)).build();
should use created response code

2023-07-27 09:50 UTC, shaunganley commented on src/main/java/org/kainos/ea/dao/BandDao.java
> +        String selectStatement = "SELECT * FROM bands;";
don't select *

2023-07-27 09:50 UTC, shaunganley commented on src/main/java/org/kainos/ea/dao/BandDao.java
> +}
not required

2023-07-27 09:50 UTC, shaunganley commented on src/main/java/org/kainos/ea/dao/CapabilityDao.java
> +    }
not required

2023-07-27 09:50 UTC, shaunganley commented on src/main/java/org/kainos/ea/exception/FailedToGetBandException.java
> +}
not required

2023-07-27 09:50 UTC, shaunganley commented on src/main/java/org/kainos/ea/exception/FailedToGetCapabilityException.java
> +
not required

2023-07-27 09:50 UTC, shaunganley commented on src/main/java/org/kainos/ea/model/Band.java
> +    }
not required

2023-07-27 09:50 UTC, shaunganley commented on src/main/java/org/kainos/ea/service/BandService.java
> +
not required

2023-07-27 09:50 UTC, shaunganley commented on src/main/java/org/kainos/ea/service/CapabilityService.java
> +        }
not required

2023-07-27 09:50 UTC, shaunganley commented on src/test/java/integration/controller/CapabilityControllerIntegrationTest.java
> +}
not required

2023-07-27 09:50 UTC, shaunganley commented on src/test/java/integration/controller/JobRoleControllerIntegrationTest.java
> +    void createJobRole_shouldReturn200_whenCreated() {
add a test with invalid data and expect a 400

2023-07-27 09:50 UTC, shaunganley commented on src/test/java/unit/controller/CapabilityControllerUnitTest.java
> +    }
not required

2023-07-27 09:50 UTC, shaunganley commented on src/test/java/unit/service/CapabilityServiceTest.java
> +}
not required

2023-07-27 09:50 UTC, shaunganley commented on src/test/java/unit/service/JobRoleServiceTest.java
> +        Mockito.when(capabilityDao.getCapabilityById(1)).thenReturn(capability);
we shouldn't be mocking these daos as they're only passed to the validator. we should be mocking the validator and add tests for exceptions being thrown

2023-07-27 09:58 UTC, joshuasy10 commented on src/main/java/org/kainos/ea/dao/BandDao.java
> +}
yes it is, its required for validation for if the band exists, we discussed this in teams

2023-07-27 10:06 UTC, joshuasy10 commented on src/main/java/org/kainos/ea/controller/BandController.java
> +    }
removed

2023-07-27 10:06 UTC, joshuasy10 commented on src/main/java/org/kainos/ea/controller/JobRoleController.java
> +            return Response.ok(jobRoleService.createJobRole(jobRoleRequest)).build();
done

2023-07-27 10:06 UTC, joshuasy10 commented on src/main/java/org/kainos/ea/dao/BandDao.java
> +        String selectStatement = "SELECT * FROM bands;";
done

2023-07-27 10:10 UTC, joshuasy10 commented on src/test/java/unit/controller/CapabilityControllerUnitTest.java
> +    }
removed

2023-07-27 10:10 UTC, joshuasy10 commented on src/test/java/integration/controller/JobRoleControllerIntegrationTest.java
> +    void createJobRole_shouldReturn200_whenCreated() {
done

2023-07-27 10:12 UTC, joshuasy10 commented on src/test/java/unit/service/CapabilityServiceTest.java
> +}
removed

2023-07-27 10:18 UTC, joshuasy10 commented on src/test/java/unit/service/JobRoleServiceTest.java
> +        Mockito.when(capabilityDao.getCapabilityById(1)).thenReturn(capability);
will this not mean i'd have to completely refactor everything to pass validator objects in contsructors?

2023-07-27 10:29 UTC, shaunganley commented on src/test/java/unit/service/JobRoleServiceTest.java
> +        Mockito.when(capabilityDao.getCapabilityById(1)).thenReturn(capability);
yes, otherwise you can't mock out the validator which means your unit tests are testing the validator class as well so aren't actual unit tests

2023-07-27 10:30 UTC, shaunganley commented on src/main/java/org/kainos/ea/dao/CapabilityDao.java
> +    }
happy that this is required in dao but not service

2023-07-27 10:42 UTC, joshuasy10 commented on src/main/java/org/kainos/ea/dao/BandDao.java
> +}
i have removed the service methods and only have Dao

2023-07-27 10:42 UTC, joshuasy10 commented on src/test/java/integration/controller/CapabilityControllerIntegrationTest.java
> +}
done

2023-07-27 11:06 UTC, joshuasy10 commented on src/test/java/unit/service/JobRoleServiceTest.java
> +        Mockito.when(capabilityDao.getCapabilityById(1)).thenReturn(capability);
done

2023-07-28 08:01 UTC, closed without merging