US015 & US012 & US020 add, edit, & delete role
KeelanScott/all_tables_api pull request #14
Opened 2023-07-28 11:09 UTC by joshuasy10

2023-07-28 11:18 UTC, jedgar3 requested changes

2023-07-28 11:18 UTC, jedgar3 commented on src/main/java/org/kainos/ea/exception/BandDoesNotExistException.java
> +        return "Capability does not exist";
This should return band does not exist rather than capability

2023-07-28 11:20 UTC, joshuasy10 commented on src/main/java/org/kainos/ea/exception/BandDoesNotExistException.java
> +        return "Capability does not exist";
forgot to push that change

2023-07-28 13:35 UTC, shaunganley requested changes

2023-07-28 13:35 UTC, shaunganley commented on src/main/java/org/kainos/ea/controller/JobRoleController.java
> +            return Response.status(Response.Status.CREATED).build();
you probably want to return and id from this endpoint so people know how to find the role they have created

2023-07-28 13:35 UTC, shaunganley commented on src/main/java/org/kainos/ea/dao/BandDao.java
> +        String selectStatement = "SELECT * FROM bands;";
no wildcards

2023-07-28 13:35 UTC, shaunganley commented on src/main/java/org/kainos/ea/service/CapabilityService.java
> +    private final CapabilityDao jobRoleDao;
bad var name

2023-07-28 13:35 UTC, shaunganley commented on src/test/java/integration/controller/JobRoleControllerIntegrationTest.java
> +        jobRoleRequest.setName(null);
create the object inside the test method

2023-07-28 13:35 UTC, shaunganley commented on src/test/java/integration/controller/JobRoleControllerIntegrationTest.java
> +                .put(javax.ws.rs.client.Entity.json(jobRoleRequest));
this test is dependent on role with id 2 existing in the db, instead you should create a role as part of this test,  get the new id and use it to update

2023-07-28 13:35 UTC, shaunganley commented on src/test/java/integration/controller/JobRoleControllerIntegrationTest.java
> +        int id = (new JobRoleService(new JobRoleDao(), new JobRoleValidator(new JobRoleDao(), new BandDao(), new CapabilityDao()))).createJobRole(jobRoleRequest);
you can just call the create a role endpoint as part of this test, get the new id and use it to delete

2023-07-28 13:35 UTC, shaunganley commented on src/test/java/unit/service/JobRoleServiceTest.java
> +        Mockito.when(jobRoleDao.createJobRole(jobRoleRequest)).thenReturn(1);
this shouldn't be mocked here

2023-07-28 13:35 UTC, shaunganley commented on src/test/java/unit/service/JobRoleServiceTest.java
> +        Mockito.when(jobRoleDao.createJobRole(jobRoleRequest)).thenReturn(1);
you're also missing the validator mock in here

2023-07-28 13:35 UTC, shaunganley commented on src/test/java/unit/service/JobRoleServiceTest.java
> +        Mockito.when(jobRoleDao.createJobRole(jobRoleRequest)).thenReturn(1);
this shouldn't be mocked here, you're also missing the validator mock in here

2023-07-28 13:35 UTC, shaunganley commented on src/test/java/unit/service/JobRoleServiceTest.java
> +        Mockito.when(jobRoleDao.createJobRole(jobRoleRequest)).thenReturn(1);
you're also missing the validator mock in here

2023-07-28 13:35 UTC, shaunganley commented on src/test/java/unit/service/JobRoleServiceTest.java
> +        Mockito.when(jobRoleDao.deleteJobRole(1)).thenReturn(false);
duplicate

2023-07-28 13:35 UTC, shaunganley commented on src/test/java/unit/service/JobRoleServiceTest.java
> +        Mockito.when(jobRoleDao.deleteJobRole(1)).thenReturn(false);
you're missing other mocks in this test

2023-07-28 13:35 UTC, shaunganley commented on src/test/java/unit/service/JobRoleServiceTest.java
> +        Mockito.when(jobRoleDao.getJobRoleById(1)).thenReturn(null);
need to test this scenario for the other endpoints

2023-07-28 13:35 UTC, shaunganley commented on src/test/java/validator/JobRoleValidatorTest.java
> +        assert(jobRoleValidator.isValidJobRole(jobRoleRequest));
assertTrue

2023-07-28 13:35 UTC, shaunganley commented on src/test/java/validator/JobRoleValidatorTest.java
> +        jobRoleRequest.setSpecification("");
define the request object in the test method

2023-07-28 13:35 UTC, shaunganley commented on src/test/java/validator/JobRoleValidatorTest.java
> +        jobRoleRequest.setSpecification("X".repeat(256));
define the request object in the test method

2023-07-28 13:35 UTC, shaunganley commented on src/test/java/validator/JobRoleValidatorTest.java
> +        jobRoleRequest.setCapabilityId(0);
define the request object in the test method

2023-07-28 13:35 UTC, shaunganley commented on src/test/java/validator/JobRoleValidatorTest.java
> +        jobRoleRequest.setBandId(0);
define the request object in the test method

2023-07-28 13:35 UTC, shaunganley commented on src/test/java/validator/JobRoleValidatorTest.java
> +        jobRoleRequest.setName("");
define the request object in the test method

2023-07-28 13:35 UTC, shaunganley commented on src/test/java/validator/JobRoleValidatorTest.java
> +        jobRoleRequest.setName("X".repeat(51));
define the request object in the test method

2023-07-31 08:11 UTC, joshuasy10 commented on src/main/java/org/kainos/ea/controller/JobRoleController.java
> +            return Response.status(Response.Status.CREATED).build();
done, think this happened after changing from ok to created and forgot to return the id again

2023-07-31 08:11 UTC, joshuasy10 commented on src/main/java/org/kainos/ea/dao/BandDao.java
> +        String selectStatement = "SELECT * FROM bands;";
done

2023-07-31 08:12 UTC, joshuasy10 commented on src/main/java/org/kainos/ea/service/CapabilityService.java
> +    private final CapabilityDao jobRoleDao;
sorted

2023-07-31 08:14 UTC, joshuasy10 commented on src/test/java/integration/controller/JobRoleControllerIntegrationTest.java
> +        jobRoleRequest.setName(null);
i have added a @BeforeEach to reset the request object each time.

2023-07-31 08:16 UTC, joshuasy10 commented on src/test/java/integration/controller/JobRoleControllerIntegrationTest.java
> +                .put(javax.ws.rs.client.Entity.json(jobRoleRequest));
done

2023-07-31 08:18 UTC, joshuasy10 commented on src/test/java/validator/JobRoleValidatorTest.java
> +        jobRoleRequest.setSpecification("X".repeat(256));
also added a @BeforeEach to reset the objects

2023-07-31 08:18 UTC, joshuasy10 commented on src/test/java/validator/JobRoleValidatorTest.java
> +        jobRoleRequest.setCapabilityId(0);
see above

2023-07-31 08:18 UTC, joshuasy10 commented on src/test/java/validator/JobRoleValidatorTest.java
> +        jobRoleRequest.setBandId(0);
see above

2023-07-31 08:18 UTC, joshuasy10 commented on src/test/java/validator/JobRoleValidatorTest.java
> +        jobRoleRequest.setName("");
see above

2023-07-31 08:19 UTC, joshuasy10 commented on src/test/java/validator/JobRoleValidatorTest.java
> +        jobRoleRequest.setName("X".repeat(51));
see above

2023-08-01 08:19 UTC, ccurran01 commented on src/main/java/org/kainos/ea/service/CapabilityService.java
> +        } catch (SQLException e) {
Could this catch be extended to include the `DatabaseConnectionException`? That way both the 500 scenarios are covered by a single exception in the controller.

2023-08-01 08:19 UTC, ccurran01 commented on src/main/java/org/kainos/ea/service/JobRoleService.java
> +        } catch (SQLException e) {
Could this catch be extended to include the `DatabaseConnectionException`? That way both the 500 scenarios are covered by a single exception in the controller.

2023-08-01 08:19 UTC, ccurran01 commented on src/main/java/org/kainos/ea/service/JobRoleService.java
> +            System.err.println(e.getMessage());
Could this catch be extended to include the `DatabaseConnectionException`? That way both the 500 scenarios are covered by a single exception in the controller.

2023-08-01 08:21 UTC, ccurran01 commented on src/main/java/org/kainos/ea/validator/JobRoleValidator.java
> +            throw new InvalidJobRoleException(e.getMessage());
Should the details of an SQL or Database Connection error be exposed to the API consumers as a 400 error?

2023-08-01 08:25 UTC, ccurran01 commented on src/test/java/integration/controller/JobRoleControllerIntegrationTest.java
> +        int id = (new JobRoleService(new JobRoleDao(), new JobRoleValidator(new JobRoleDao(), new BandDao(), new CapabilityDao()))).createJobRole(jobRoleRequest);
Could this outstanding comment from @shaunganley be addressed. I think I agree with his suggestion of going through the endpoint.

2023-08-01 08:28 UTC, ccurran01 commented on src/test/java/unit/service/JobRoleServiceTest.java
> +        Mockito.when(jobRoleDao.createJobRole(jobRoleRequest)).thenReturn(1);
Agree with @shaunganley suggestions. Could we remove the create role mock, the job role create function isn't called during in the service method to update a role. The job role validator is called though and there is a missing when call for that

2023-08-01 08:30 UTC, ccurran01 commented on src/test/java/unit/service/JobRoleServiceTest.java
> +        Mockito.when(jobRoleDao.createJobRole(jobRoleRequest)).thenReturn(1);
Lets remove this when for the createJobRole and add in the when call for the validator

2023-08-01 08:30 UTC, ccurran01 commented on src/test/java/unit/service/JobRoleServiceTest.java
> +        Mockito.when(jobRoleDao.createJobRole(jobRoleRequest)).thenReturn(1);
Lets remove this when for the createJobRole and add in the when call for the validator

2023-08-01 08:31 UTC, ccurran01 commented on src/test/java/unit/service/JobRoleServiceTest.java
> +        Mockito.when(jobRoleDao.getJobRoleById(1)).thenReturn(null);
This scenario seems to be missing for the delete and update functions.

2023-08-01 08:32 UTC, ccurran01 commented on src/test/java/unit/service/JobRoleServiceTest.java
> +        Mockito.when(jobRoleDao.deleteJobRole(1)).thenReturn(false);
This when statement is duplicated with the one below

2023-08-01 08:34 UTC, ccurran01 commented on src/test/java/unit/service/JobRoleServiceTest.java
> +        Mockito.when(jobRoleDao.deleteJobRole(1)).thenReturn(false);
Are we not missing a when call for getJobRoleById

2023-08-01 08:35 UTC, ccurran01 commented on src/test/java/validator/JobRoleValidatorTest.java
> +        assert(jobRoleValidator.isValidJobRole(jobRoleRequest));
Could we address @shaunganley's comment please

2023-08-01 09:13 UTC, joshuasy10 commented on src/main/java/org/kainos/ea/service/BandService.java
> +        } catch (SQLException e) {
done

2023-08-01 09:14 UTC, joshuasy10 commented on src/main/java/org/kainos/ea/service/CapabilityService.java
> +        } catch (SQLException e) {
done

2023-08-01 09:15 UTC, joshuasy10 commented on src/main/java/org/kainos/ea/service/JobRoleService.java
> +        } catch (SQLException e) {
done

2023-08-01 09:15 UTC, joshuasy10 commented on src/main/java/org/kainos/ea/service/JobRoleService.java
> +            System.err.println(e.getMessage());
done

2023-08-01 09:25 UTC, joshuasy10 commented on src/main/java/org/kainos/ea/service/JobRoleService.java
> +        } catch (SQLException e) {
done

2023-08-01 09:27 UTC, joshuasy10 commented on src/main/java/org/kainos/ea/validator/JobRoleValidator.java
> +            throw new InvalidJobRoleException(e.getMessage());
done

2023-08-01 10:06 UTC, joshuasy10 commented on src/test/java/integration/controller/JobRoleControllerIntegrationTest.java
> +        int id = (new JobRoleService(new JobRoleDao(), new JobRoleValidator(new JobRoleDao(), new BandDao(), new CapabilityDao()))).createJobRole(jobRoleRequest);
done

2023-08-01 10:06 UTC, joshuasy10 commented on src/test/java/integration/controller/JobRoleControllerIntegrationTest.java
> +        int id = (new JobRoleService(new JobRoleDao(), new JobRoleValidator(new JobRoleDao(), new BandDao(), new CapabilityDao()))).createJobRole(jobRoleRequest);
done

2023-08-02 09:37 UTC, shaunganley approved these changes

2023-08-02 12:41 UTC, merged