001, 002, 003 view job roles with band and capability
KeelanScott/all_tables_api pull request #7
Opened 2023-07-19 14:15 UTC by joshuasy10

This includes 001, 002, & 003
GET /api/job-roles
returns list of job roles including the associated band and capability.

includes alterations regarding PR comments

2023-07-19 14:22 UTC, jedgar3 commented on src/main/java/org/kainos/ea/controller/JobRoleController.java
I will merge this branch onto mine to make the necessary changes to make viewing by id endpoint work

2023-07-19 14:23 UTC, jedgar3 commented on src/main/java/org/kainos/ea/dao/JobRoleDao.java
I  will merge this branch onto mine to make the necessary changes to make viewing by id method work

2023-07-19 14:26 UTC, jedgar3 approved these changes
The file changes look good, currently working on viewing by id to get the tests and the endpoint running again.

2023-07-19 14:26 UTC, jedgar3 commented on src/main/java/org/kainos/ea/service/JobRoleService.java
I  will merge this branch onto mine to make the necessary changes to make viewing by id in the service class working

2023-07-20 07:38 UTC, shaunganley requested changes
needs integration tests, controller unit tests and lots of things to clean up that aren't required

2023-07-20 07:38 UTC, shaunganley commented on src/main/java/org/kainos/ea/controller/JobRoleController.java
> +
remove whitespace

2023-07-20 07:38 UTC, shaunganley commented on src/main/java/org/kainos/ea/dao/JobRoleDao.java
> +
remove whitespace

2023-07-20 07:38 UTC, shaunganley commented on src/main/java/org/kainos/ea/dao/JobRoleDao.java
> +        assert c != null;
this shouldn't be here, logic for recreating the connection should be in the DatabaseConnector.getConnection() method

2023-07-20 07:38 UTC, shaunganley commented on src/main/java/org/kainos/ea/exception/JobRoleNameTooLongException.java
> +    }
remove not needed

2023-07-20 07:38 UTC, shaunganley commented on src/main/java/org/kainos/ea/exception/JobRoleSpecificationTooLongException.java
> +        return "Job role specification must be less than 255 characters";
remove not needed

2023-07-20 07:38 UTC, shaunganley commented on src/main/java/org/kainos/ea/model/JobRoleRequest.java
> +    public int getBandId() {
remove not needed

2023-07-20 07:38 UTC, shaunganley commented on src/main/java/org/kainos/ea/service/JobRoleService.java
> +
remove whitespace

2023-07-20 07:38 UTC, shaunganley commented on src/test/java/org/kainos/ea/service/JobRoleServiceTest.java
> +    JobRoleService jobRoleService = new JobRoleService(jobRoleDao);
you're not actually passing the mocked databaseConnector in here

2023-07-20 07:38 UTC, shaunganley commented on src/test/java/org/kainos/ea/service/JobRoleServiceTest.java
> +            "Develops Software"
remove not needed

2023-07-20 07:38 UTC, shaunganley commented on src/test/java/org/kainos/ea/service/JobRoleServiceTest.java
> +    @Test
add unit test for the exception scenario

2023-07-20 08:13 UTC, joshuasy10 commented on src/main/java/org/kainos/ea/exception/JobRoleNameTooLongException.java
> +    }
You said to remove things that weren't in the scope of my user stories.

2023-07-20 08:14 UTC, joshuasy10 commented on src/main/java/org/kainos/ea/model/JobRoleRequest.java
> +    public int getBandId() {
This also is unrelated to my user stories as I am at this moment only getting data and not posting/putting data.

2023-07-20 08:21 UTC, joshuasy10 commented on src/test/java/org/kainos/ea/service/JobRoleServiceTest.java
> +            "Develops Software"
This isnt used in my user stories or tests

2023-07-20 08:24 UTC, joshuasy10 commented on src/main/java/org/kainos/ea/service/JobRoleService.java
> +
done

2023-07-20 08:25 UTC, joshuasy10 commented on src/test/java/org/kainos/ea/service/JobRoleServiceTest.java
> +    JobRoleService jobRoleService = new JobRoleService(jobRoleDao);
removed unnecessary line 25

2023-07-20 08:25 UTC, joshuasy10 commented on src/test/java/org/kainos/ea/service/JobRoleServiceTest.java
> +    @Test
done

2023-07-20 10:58 UTC, jedgar3 commented
Test failed due to using data type int instead of string

2023-07-20 11:07 UTC, jedgar3 requested changes

2023-07-20 11:07 UTC, jedgar3 commented on src/main/java/org/kainos/ea/all_tables_apiConfiguration.java
Thanks for making my suggested fix due to running with different folder names

2023-07-20 11:07 UTC, jedgar3 commented on src/main/java/org/kainos/ea/dao/DatabaseConnector.java
Good work for changing package names

2023-07-20 11:07 UTC, jedgar3 commented on src/test/java/org/kainos/ea/service/JobRoleServiceTest.java
> +    Connection conn;
Do we need this variable, I dont think it is being used, please remove

2023-07-20 11:09 UTC, jedgar3 approved these changes

2023-07-20 11:09 UTC, jedgar3 commented on src/test/java/org/kainos/ea/service/JobRoleServiceTest.java
Job job making those requested fixes

2023-07-20 12:19 UTC, shaunganley requested changes
good job, please add unit tests for controller class and address other comments

2023-07-20 12:19 UTC, shaunganley commented on src/main/java/org/kainos/ea/exception/JobRoleNameTooLongException.java
> +    }
correct, why is this needed?

2023-07-20 12:19 UTC, shaunganley commented on src/main/java/org/kainos/ea/exception/JobRoleSpecificationTooLongException.java
> +        return "Job role specification must be less than 255 characters";
why is this needed?

2023-07-20 12:19 UTC, shaunganley commented on src/main/java/org/kainos/ea/model/JobRoleRequest.java
> +    public int getBandId() {
exactly, why is this needed?

2023-07-20 12:19 UTC, shaunganley commented on src/test/java/org/kainos/ea/service/JobRoleServiceTest.java
> +            "Develops Software"
exactly, so can you remove it?

2023-07-20 12:19 UTC, shaunganley commented on src/main/java/org/kainos/ea/dao/JobRoleDao.java
> +        Connection c = DatabaseConnector.getConnection();
if you pass this in as a param you will be able to mock it out and test exception handling logic in the service layer

2023-07-20 12:38 UTC, joshuasy10 commented on src/main/java/org/kainos/ea/exception/JobRoleNameTooLongException.java
> +    }
sorry i thought i removed this and you where asking why, this will be removed

2023-07-20 12:40 UTC, joshuasy10 commented on src/main/java/org/kainos/ea/model/JobRoleRequest.java
> +    public int getBandId() {
again I thought I removed this, I must have accidentally merged James' work

2023-07-20 15:15 UTC, jedgar3 requested changes

2023-07-20 15:15 UTC, jedgar3 commented on .github/workflows/maven.yml
Great job adding secrets and using environment variables

2023-07-20 15:15 UTC, jedgar3 commented on src/test/java/org/kainos/ea/controller/JobRoleControllerUnitTest.java
> +//    @Test
Why is this commented out

2023-07-20 15:17 UTC, jedgar3 approved these changes

2023-07-21 08:12 UTC, shaunganley reviewed
great work on this. really close to being ready. few small comments. make sure github actions is actually running your unit and integration tests

2023-07-21 12:24 UTC, shaunganley requested changes

2023-07-21 12:24 UTC, shaunganley commented on src/test/java/org/kainos/ea/controller/JobRoleControllerIntegrationTest.java
> +package org.kainos.ea.controller;
move this to an integration test folder to keep separate for unit tests, make it easier to run them in isolation

2023-07-24 09:05 UTC, jedgar3 approved these changes

2023-07-24 09:05 UTC, jedgar3 commented on src/main/java/org/kainos/ea/cli/temp empty file to commit folder
Good job removing unused files

2023-07-24 09:05 UTC, jedgar3 commented on src/test/java/integration/controller/JobRoleControllerIntegrationTest.java
Ousttanding work by adding an integration tests folder to seperate the unit tests and the integration tests

2023-07-24 09:22 UTC, shaunganley approved these changes
ready for testing

2023-07-25 10:07 UTC, merged