002 view job spec
KeelanScott/all_tables_api pull request #9
Opened 2023-07-24 10:34 UTC by jedgar3

Merged with Josh's approved files to keep things in the same place

2023-07-24 10:46 UTC, joshuasy10 requested changes
See comments, need to remove white space in places and remove extra constructors and refactor code to use just one.

2023-07-24 10:46 UTC, joshuasy10 commented on src/main/java/org/kainos/ea/dao/DatabaseConnector.java
remove white space

2023-07-24 10:46 UTC, joshuasy10 commented on src/main/java/org/kainos/ea/exception/DatabaseConnectionException.java
Outstanding

2023-07-24 10:46 UTC, joshuasy10 commented on src/main/java/org/kainos/ea/model/Capability.java
> +    public Capability(int id, String name, String description) {
remove extra constructors and use only one in your code please

2023-07-24 10:46 UTC, joshuasy10 commented on src/main/java/org/kainos/ea/model/JobRole.java
> +
remove whitespace

2023-07-24 10:46 UTC, joshuasy10 commented on src/main/java/org/kainos/ea/model/JobRole.java
> +    public JobRole(int id, String name, Band band, String specifictaion) {
remove extra constructor and refactor code to just have one.

2023-07-24 10:46 UTC, joshuasy10 commented on src/main/java/org/kainos/ea/service/JobRoleService.java
> +
remove whitespace

2023-07-24 10:46 UTC, joshuasy10 commented on src/test/java/unit/controller/JobRoleControllerUnitTest.java
fantastic

2023-07-24 13:05 UTC, joshuasy10 approved these changes

2023-07-25 11:18 UTC, shaunganley requested changes
good work, few small comments

2023-07-25 11:18 UTC, shaunganley commented on src/main/java/org/kainos/ea/controller/JobRoleController.java
> +        } catch (DatabaseConnectionException e) {
bad request suggests that the user passed incorrect data in but they don't pass any data to this endpoint, please combine both catch blocks to return 500

2023-07-25 11:18 UTC, shaunganley commented on src/main/java/org/kainos/ea/dao/JobRoleDao.java
> +                    null
not sure why you need to pass null here? if you don't want to return the specification for this endpoint then create a new constructor that doesn't accept it or create a new response model that has a specification

2023-07-25 11:18 UTC, shaunganley commented on src/main/java/org/kainos/ea/dao/JobRoleDao.java
> +            band.setLevel(rs.getString("level"));
create a constructor to pass the through in 1 line

2023-07-25 11:18 UTC, shaunganley commented on src/main/java/org/kainos/ea/model/JobRole.java
> +                   @JsonProperty("Capability") Capability capability,
```suggestion
                   @JsonProperty("capability") Capability capability,
```

2023-07-25 11:18 UTC, shaunganley commented on src/main/java/org/kainos/ea/service/JobRoleService.java
> +                throw new FailedToGetJobRoleException();
this should be a JobRoleDoesNotExist exception which should return a 404 from controller, FailedToGetJobRoleException should return a 500

2023-07-25 11:18 UTC, shaunganley commented on src/test/java/unit/service/JobRoleServiceTest.java
> +    void getJobRolesById_shouldThrowFailedToGetJobRoleException_whenDaoReturnsNull() throws SQLException, DatabaseConnectionException {
need another unit test for SQLException being thrown

2023-07-25 13:17 UTC, joshuasy10 approved these changes

2023-07-25 13:17 UTC, joshuasy10 commented on src/main/java/org/kainos/ea/controller/JobRoleController.java
> +        } catch (DatabaseConnectionException | FailedToGetJobRoleException e) {
Unbelievable stuff!

2023-07-25 13:17 UTC, joshuasy10 commented on src/main/java/org/kainos/ea/exception/JobRoleDoesNotExistException.java
> +        return "Job role does not exist";
Bloody fantastic!

2023-07-25 13:17 UTC, joshuasy10 commented on src/main/java/org/kainos/ea/model/Band.java
> +
Remove unneccessary constructor

2023-07-25 13:17 UTC, joshuasy10 commented on src/main/java/org/kainos/ea/model/JobRole.java
> -
amazing removal of white space!

2023-07-25 13:17 UTC, joshuasy10 commented on src/main/java/org/kainos/ea/model/JobRole.java
> +                   @JsonProperty("band") Band band,
great debugging!

2023-07-25 13:17 UTC, joshuasy10 commented on src/test/java/unit/service/JobRoleServiceTest.java
> +            capability,
great stuff!

2023-07-25 13:56 UTC, shaunganley commented on src/main/java/org/kainos/ea/model/Band.java
> +    }
why do we need this constructor? can't we use the existing constructor and return the band ID?

2023-07-25 14:00 UTC, shaunganley approved these changes

2023-07-25 14:40 UTC, merged